#%RAML 1.0 Trait
# this is a RAML 1.0 trait fragment indicated by its first line
queryParameters:
  maxResults:
    displayName: Maximum Number of Records.
    description: |
      The maximum number of entries to return. This is optional.
    type: integer
    default: 25
    required: false
  offset:
    displayName: Starting from Record
    description: |
      The 1-based index of the first result to be retrieved (for paging).
    type: integer
    minimum: 0
    default: 0
    required: false
  orderBy:
    displayName: Order by
    description: |
      Fields to order by (lowercase).
    type: string
    required: false
  order:
    displayName: Order
    description: |
      Ascending or descending order
    type: string
    enum: [asc, desc]
    required: false