#%RAML 1.0 DataType

#This file is located at dataTypes/Address.raml

type: object
properties:
  street?: string
  street2?: string
  city?: string
  state?: string
  postalCode?: string
  country?: string