#%RAML 1.0
title: Account System API
version: v2.0
baseUri: http://localhost:8081/api
  
types: 
  address: !include dataTypes/Address.raml
  account: !include dataTypes/Account.raml
  errorResponse: !include dataTypes/ErrorResponse.raml
  successResponse: !include dataTypes/SuccessResponse.raml

traits:
  accountSearch: !include traits/trait-collection.raml

/accounts:
  description: |
    Working with accounts:
    * Retrieving all accounts
    * Creating accounts
  get:
    displayName: Get accounts
    description: |
      Retrieve all Accounts.
    is: [ accountSearch ]
    queryParameters:
      name:
        displayName: The account name
        minLength: 0
        maxLength: 255
        required: false
      match:
        displayName: The account name matching rule
        description: |
          The account name matching rule
        type: string
        enum: [like, equals]
        default: equals
        required: false
      modifiedAfter:
        displayName: Only those modified after this date
        minLength: 23
        maxLength: 29
        required: false
        example: 2016-04-28T14:00:00.000Z
      modifiedBefore:
        displayName: Only those modified before this date
        minLength: 23
        maxLength: 29
        required: false
        example: 2016-05-28T14:00:00.000Z
    responses:
      200:
        body:
          application/json:
            type: account[]
            example: !include examples/get_accounts_example.yaml
  post:
    displayName: Create account
    description: |
      Create a new Account
    body:
      application/json:
        type: account
        example: !include examples/post_account_example.yaml
    responses:
      201:
        body:
          application/json:
            type: account
            example: |
              {
                "id": "0012000001BaRgPAAV",
                "name": "Example Company"
              }
      400:
        body:
          application/json:
            type: errorResponse
            example: |
              {
                "message": "Failed to create new Account"
              }
  /{id}:
    description: |
      Working with accounts:
      * Retrieving specific account
      * Updating specific account
      * Deleting specific account
    uriParameters:
      id:
        type: string
        example: 0012000001BaRgPAAV
        description: Represents the account unique id
    get:
      displayName: Get account by id
      description: Get Account by ID
      responses:
        200:
          body:
            application/json:
              type: account
              example: !include examples/get_accountById_example.yaml
        404:
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "Resource not found"
                }
    put:
      displayName: Update account by id
      description: Update Account specified by ID
      body:
        application/json:
          type: account
          example: !include examples/put_account_example.yaml
      responses:
        200:
          body:
            application/json:
              type: successResponse
              example: |
                {
                  "status": "OK"
                }
        404:
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "Resource not found"
                }
    delete:
      displayName: Delete account by id
      description: Delete Account specified by ID
      responses:
        200:
          body:
            application/json:
              type: successResponse
              example: |
                {
                  "status": "OK"
                }
        404:
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "Resource not found"
                }