#%RAML 1.0 DataType

#This file is located at dataTypes/account.raml

type: object
properties: 
  id?: string
  nativeId?: string
  name?: string
  phone?: string
  email?: string
  createdDate?: string
  billingStreet?: string
  billingCity?: string
  billingState?: string
  billingPostalCode?: string
  billingCountry?: string
  shippingStreet?: string
  shippingCity?: string
  shippingState?: string
  shippingPostalCode?: string
  shippingCountry?: string
  lastModifiedDate?: string
  lastModifiedById?: string